package hbi.core.org.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import com.hand.hap.core.annotation.MultiLanguage;
import com.hand.hap.core.annotation.MultiLanguageField;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@MultiLanguage
@Table(name = "cin_circ_reporting_orgs")
public class CircReportingOrgs extends BaseDTO {

     public static final String FIELD_REP_ORG_ID = "repOrgId";
     public static final String FIELD_REP_ORG_CODE = "repOrgCode";
     public static final String FIELD_REP_ORG_NAME = "repOrgName";
     public static final String FIELD_REP_ORG_DESC = "repOrgDesc";
     public static final String FIELD_REP_ORG_TYPE = "repOrgType";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_START_DATE_ACTIVE = "startDateActive";
     public static final String FIELD_END_DATE_ACTIVE = "endDateActive";
     public static final String FIELD_FT_FLEX_CODE = "ftFlexCode";
     public static final String FIELD_TX_FLEX_CODE = "txFlexCode";


     @Id
     @GeneratedValue
     private Long repOrgId;

     @Length(max = 50)
     private String repOrgCode; //报送机构代码
    @MultiLanguageField
     @Length(max = 100)
     private String repOrgName; //报送机构名称
    @MultiLanguageField
     @Length(max = 50)
     private String repOrgDesc; //报送机构说明

     @Length(max = 50)
     private String repOrgType; //机构类型

     @Length(max = 1)
     private String enabledFlag; //启用标志

     private Date startDateActive;

     private Date endDateActive;

     @Length(max = 20)
     private String ftFlexCode; //分摊应用编码

     @Length(max = 20)
     private String txFlexCode; //统信引用编码


     public void setRepOrgId(Long repOrgId){
         this.repOrgId = repOrgId;
     }

     public Long getRepOrgId(){
         return repOrgId;
     }

     public void setRepOrgCode(String repOrgCode){
         this.repOrgCode = repOrgCode;
     }

     public String getRepOrgCode(){
         return repOrgCode;
     }

     public void setRepOrgName(String repOrgName){
         this.repOrgName = repOrgName;
     }

     public String getRepOrgName(){
         return repOrgName;
     }

     public void setRepOrgDesc(String repOrgDesc){
         this.repOrgDesc = repOrgDesc;
     }

     public String getRepOrgDesc(){
         return repOrgDesc;
     }

     public void setRepOrgType(String repOrgType){
         this.repOrgType = repOrgType;
     }

     public String getRepOrgType(){
         return repOrgType;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setStartDateActive(Date startDateActive){
         this.startDateActive = startDateActive;
     }

     public Date getStartDateActive(){
         return startDateActive;
     }

     public void setEndDateActive(Date endDateActive){
         this.endDateActive = endDateActive;
     }

     public Date getEndDateActive(){
         return endDateActive;
     }

     public void setFtFlexCode(String ftFlexCode){
         this.ftFlexCode = ftFlexCode;
     }

     public String getFtFlexCode(){
         return ftFlexCode;
     }

     public void setTxFlexCode(String txFlexCode){
         this.txFlexCode = txFlexCode;
     }

     public String getTxFlexCode(){
         return txFlexCode;
     }

     }
