package hbi.core.fnd.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "fnd_flex_structures")
public class FlexStructures extends BaseDTO {

     public static final String FIELD_APPLICATION_ID = "applicationId";
     public static final String FIELD_ID_FLEX_CODE = "idFlexCode";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";
     public static final String FIELD_ID_FLEX_NAME = "idFlexName";
     @Id
     @GeneratedValue
     private Long applicationId;
     @NotEmpty
     @Length(max = 100)
     private String idFlexCode;
     @NotEmpty
     @Length(max = 100)
     private String enabledFlag;
     @Length(max = 240)
     private String idFlexName;

     public void setApplicationId(Long applicationId){
         this.applicationId = applicationId;
     }

     public Long getApplicationId(){
         return applicationId;
     }

     public void setIdFlexCode(String idFlexCode){
         this.idFlexCode = idFlexCode;
     }

     public String getIdFlexCode(){
         return idFlexCode;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     public void setIdFlexName(String idFlexName){
         this.idFlexName = idFlexName;
     }

     public String getIdFlexName(){
         return idFlexName;
     }

     }
